### ISSUE TITLE
Implement a command to inspect Jelly files

### ISSUE THREAD

**Issue by Ostrzyciel** [Jelly-RDF/cli#39]
Something like `jelly-cli rdf inspect <input-file>` or read from stdin

Would respond with a human-readable summary of what the stream is:

- Delimited or not
- Frame count
- Total row count
- Stream options (if present) or a message warning that they are not present
- Total statement (triple or quad) count

Later we can tack on more statistics about lookups and so on.

**Comment by bswck** [comment]
Here's a request from me.
User story:

> As a Jelly implementer, I'd like to see how many rows of what kind were sent in each frame.
> For checking how stream options interact with my implementation, I need them included in the report.

I have an instinct that a very wise thing to do would be to produce the output in the human-friendly format YAML, so that these statistics can be processed automatically, whenever such need arises.

Here's an example:

```yaml
stream_options:
- physical_type: 1
- generalized_statements: 1
- rdf_star: 1
- max_name_table_size: 128
- max_prefix_table_size: 16
- max_datatype_table_size: 16
- logical_type: 1
- version: 1

total-frames: ...

frames:
# frame 0
- name: 34
  options: 1
  prefix: 80
  triple: 75
```

It would be very useful to include frame numbers in comments, unless you have a YAML library without support for round-trip serialization, then it's not that important. You can always add a property called `_number`.

This is the most useful addition for development I'd imagine.
